/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panels;

import ij.ImagePlus;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import loci.formats.FormatException;
import loci.plugins.BF;
import org.imgscalr.Scalr;

/**
 *
 * @author andy
 */
public class ImagePanel extends javax.swing.JPanel {
    
//    ImagePlus imp;
    private BufferedImage image, resized;
    
    public ImagePanel() {
        initComponents();
    }
    
    public void updateImage(ImagePlus imp) {
        resized = Scalr.resize(imp.getBufferedImage(), this.getWidth(), this.getHeight());
        repaint();
    }
    
    public void updateImage(String path) {
        try {
            ImagePlus imp = (BF.openImagePlus((new File(path)).getAbsolutePath()))[0];
            resized = Scalr.resize(imp.getBufferedImage(), this.getWidth(), this.getHeight());
        } catch (IOException | FormatException ex) {
            Logger.getLogger(ImagePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int x = 0, y = 0;
        try {
            x = (this.getWidth() - resized.getWidth()) / 2;
            y = (this.getHeight() - resized.getHeight()) / 2;
            g.drawImage(resized, x, y, null);
        } catch(NullPointerException e) {
            // nullpointerexception on startup, ignore
        } finally {
            g.drawImage(resized, x, y, null);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
